on:
  [push, workflow_dispatch]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - id: foo
        uses: ./.github/composite-action
        with:
          who-to-greet: Penguin
      - run: echo "Random Number is $RANDOM_NUMBER"
        shell: bash
        env:
          RANDOM_NUMBER: ${{ steps.foo.outputs.random-number }}

  call_workflow_passing_data:
    name: A job to run reusable workflow
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/reusable-workflow.yaml
    with:
      config-path: .github/labeler.yaml
    secrets:
      personal_access_token: ${{ secrets.GITHUB_TOKEN }}

